# Wipe Out(15)/Topkill(1)/Gathering(3)/Exploration(3+)

## == Monday ==
Port_Skandia        = { W: Mishchievous_Bunnyhop(264, 252), E: true}
Helonia_Coast       = { E: true }
Crescent_Hill       = { W: Tribal_Patrolman(454, 283), T: Senka, DNG(solo), G: NutTree(808, 683), E: true }
Cactakara_Forest    = { G: SourFruitTree(589, 88), G: MineralRichDirt(460, 125), E: true }
Demarech_Mine       = { W: Bloodthirsty_Lion(321, 174), T: Gebast }
Triatio_Highlands   = { W: Swift_Toucant(146, 731), G: CoconutTree(375, 330) }
Candeo_Marsh        = { T: Earl, DNG(solo), E: true }
Ventos_Prairie      = { W: Algae_Waterling(534, 289), T: Perihelion }
Star_Sand_Desert    = { W: Cursed_Demon_Beast(447, 779), T: Tania, DNG(solo), G: SteelCopperDeposit(416, 478), PetrifiedCoral(466, 554) }
Blizzard_Berg       = { E: true }
Rainmist_Reach      = { T: Beyeta }
Emerald_Marsh       = { W: Palmtail_Chinchilla(587, 712), T: Calona, E: true }
Starstruck_Plateau  = { W: Highland_Forest_Deer(609, 497), E: true }
Silent_Ice_Field    = { T: Naliya, G: FloodedMineral(284, 392) }
Port_Morton         = { T: Minerva, G: SmallFlowerCrab(572, 435), E: true }
Candetonn_Hill      = { T: Fidel }
Viridian_Steppe     = { W: Falcon_Harpy(205, 395), T: Talusha }
Desolate_Valley     = { T: Luigi, G: CliffFlower(724, 185), E: true }
Tanglevine_Cascades = { T: Skirr }
Sunhunters_Vale     = { T: Iniquitus }
Chronology_Forest   = { T: Ignis }
Tempest_Desert      = { T: Anima, G: PlateauBarley(711, 595), ValleyMine(735, 368), E: true }
Frigga_Peak         = { T: Angel }
Desolate_Desert     = { T: Lantao, G: LifeHerb(745, 487) }
Secret_Forest_Lake  = { T: Hurcan, Ludani }
Gloomy_Ridge        = { T: Andumalli, E: true }
Drowsy_Cave         = { T: Simachemo, G: GlowingOre(253, 321), CherrySunflower(608, 517) }

## == Tuesday ==
Port_Skandia        = { W: Sunbird(476, 488),TGE}
Helonia_Coast       = { T: Kalna }
Crescent_Hill       = { W: Mainframe_Soldier(803, 664), T: Varis, G: PatternedGrass(488, 247), RoughPurpleGemstone(553, 109) }
Cactakara_Forest    = { T: DNG(solo), G: EnergizingCabbage(343, 515) }
Demarech_Mine       = { W: Slimeling(220, 394), T: Yimis, E: true }
Triatio_Highlands   = { T: DNG(solo), G: HighlandWheat(324, 607), PrehistoricStone(294, 229), E: true }
Candeo_Marsh        = { W: Arachnid(695, 664), T: Neban }
Ventos_Prairie      = { W: Speedy_Antelope(785, 634),}
Oblitus_Wood        = { T: Grinder }
Star_Sand_Desert    = { W: Giant_Mountain_Dragon(413, 600), T: Grim, E: true }
Vultures_Vale       = { E: true }
Rainmist_Reach      = { T: Darlak, G: ShellfishCluster(518, 522), E: true }
Emerald_Marsh       = { W: Foehn_Drake(415, 716), }
Starstruck_Plateau  = { T: Gullah, E: true }
Silent_Ice_Field    = { W: Demonic_Vanguard(291, 441), T: Biggof }
Port_Morton         = { T: Dudley, G: MoonlightFlowerBushel(358, 397) }
Candetonn_Hill      = { E: true }
Viridian_Steppe     = { W: Starlight_Golem(178, 588), T: Ribbitt, G: WeatheredUnrefinedOre(522, 441) }
Tanglevine_Cascades = { T: Zeebris, G: StarfruitBush(546, 305), E: true }
Chronology_Forest   = { T: Blooma, E: true }
Tempest_Desert      = { G: Saffron(492, 648), ShockedVein(476, 405) }
Frigga_Peak         = { T: Sarge }
Desolate_Desert     = { G: SnakeDragonEgg(610, 746) }
Secret_Forest_Lake  = { T: Webster, Amutate }
Gloomy_Ridge        = { T: Flauros, E: true }
DrowsyCave          = { G: OrchidBulb(546, 134) }

## == Wednesday ==
Navea               = { G: Mushroom(335, 419) }
Helonia_Coast       = { W: Emeralden_Snail(356, 551), T: Beita, G: RainbowGrove(131, 705), E: true }
Crescent_Hill       = { W: Navean_Birdbrain(414, 791), G: AquamarineCluster(798, 707) }
Cactakara_Forest    = { T: LonerMk.XI, E: true }
Demarech_Mine       = { W: Fierce_Rock_Beetle(263, 708), T: Galen, DNG(solo), G: NestOfTwig(499, 298) }
Triatio_Highlands   = { G: LargeAmberOre(523, 650) }
Candeo_Marsh        = { W: Fanged_Bat(433, 316), T: Maro, DNG(solo), G: GarlicPlant(450, 230), E: true }
Ventos_Prairie      = { E: true }
Oblitus_Wood        = { W: Silverflash_Porter(217, 635), T: Jesper, DNG(solo), E: true }
Star_Sand_Desert    = { W: CurlyTailed_Chameleon(561, 386)}
Rainmist_Reach      = { T: Michelle, G: ShiningMeteorMineralVein(628, 331), E: true }
Emerald_Marsh       = { W: Dark_Gremlin(197, 678), G: BluePatternedFlower(354, 462) }
Starstruck_Plateau  = { T: Blessa }
Silent_Ice_Field    = { W: Crystal_Sprite(509, 679), E: true }
Port_Morton         = { T: Tamir }
Candetonn_Hill      = { G: MilkBarrel(413, 603) }
Viridian_Steppe     = { T: Damian, E: true }
Desolate_Valley     = { W: Beserk_Gelu_Combatant(212, 392), G: ElementFossil(155, 353) }
Tanglevine_Cascades = { T: Pangarian, G: CrystalbeadBlossom(341, 741) }
Sunhunters_Vale     = { E: true }
Chronology_Forest   = { T: Floda }
Tempest_Desert      = { E: true }
Frigga_Peak         = { T: Desdemonia }
Secret_Forest_Lake  = { T: Arcturus }
Gloomy_Ridge        = { T: Valak }
Drowsy_Cave         = { E: true }

## == Thursday ==
Navea               = { G: NaveaHerb(338, 543) }
Port_Skandia        = { E: true }
Helonia_Coast       = { W: Sanday_Mollusk(613, 374), T: Wade, G: HotPepperTree(428, 358) }
Crescent_Hill       = { T: DNG(solo), E: true }
Cactakara_Forest    = { W: Leathery_Crocodile(335, 345), T: SeekerL_Type, G: IndigoCrystalCluster(496, 499)}
Demarech_Mine       = { W: Keeper_Golem(788, 394), T: Otto, G: DemarechFruitTree(313, 398) }
Triatio_Highlands   = { T: DNG(solo) }
Candeo_Marsh        = { W: Stone_Forest_Turtle(599, 661), T: Weily, G: CocoaTree(384, 166) }
Ventos_Prairie      = { T: DNG(solo), E: true }
Oblitus_Wood        = { W: Butterfly_Hoplite(675, 225), T: Barthold, G: JadeVein(791, 459) }
Star_Sand_Desert    = { T: DNG(solo), E: true }
Vultures_Vale       = { E: true }
Rainmist_Reach      = { W: Forest_Fox(122, 326), T: Dinglebert, G: CloudMeteorMineral(411, 201) }
Emerald_Marsh       = { W: Emerald_Iguana(629, 494), E: true }
Starstruck_Plateau  = { T: Mandisa, G: PlateauCornPlant(667, 275) }
Silent_Ice_Field    = { W: Darkwing_Servant(777, 174) }
Port_Morton         = { T: Kermit, E: true }
Candetonn_Hill      = { G: WildFig(468, 417) }
Viridian_Steppe     = { T: Paroyagi, G: EmeraldCrystal(432, 674) }
Desolate_Valley     = { W: Demon_Patrolman(506, 437), E: true }
Tanglevine_Cascades = { T: Desdemonia, E: true }
Sunhunters_Vale     = { G: MarshCap(799, 397) }
Chronology_Forest   = { T: Buchon, E: true }
Frigga_Peak         = { T: Jeni }
Secret_Forest_Lake  = { T: Berg }
Gloomy_Ridge        = { T: Aethelmon }
Drowsy_Cave         = { E: true }

## == Friday ==
Navea               = { G: StardustFlower(536, 421) }
Helonia_Coast       = { W: Helonia_Cliff_Golem(503, 514), T: Sloar, G: SweetGrass(534, 435), E: true }
Cactakara_Forest    = { W: Abandoned_Robot_Soldier(302, 531), T: DestroyerG800, DNG(solo), G: SilverVein(512, 388)}
Demarech_Mine       = { G: OasisSpice(268, 499), E: true }
Triatio_Highlands   = { W: Hooked_Toucant(859, 526), T: Magoo, E: true }
Candeo_Marsh        = { W: Chaos_Unicorn(809, 576), T: DNG(solo) }
Ventos_Prairie      = { T: Asceldar, G: WindSpiceBush(559, 492), GlimmeringStone(449, 169) }
Oblitus_Wood        = { W: Grasslands_Sasquack(474, 732), T: Gomory, DNG(solo), E: true }
Blizzard_Berg       = { E: true }
Rainmist_Reach      = { W: Woodbeast_Hunter(448, 315), G: FlamingMineralVein(154, 472), E: true }
Emerald_Marsh       = { T: Marco }
Starstruck_Plateau  = { W: Grey_Skeletal_Hound(299, 403), T: Olmino, G: VultureNest(212, 601) }
Silent_Ice_Field    = { W: Demonic_Royal_Guard(320, 120), E: true }
Candetonn_Hill      = { T: Osmond, E: true }
Viridian_Steppe     = { G: ScalefruitBrush(471, 538), E: true }
Desolate_Valley     = { W: Spike_Scorpion(414, 738), T: Stalteri, G: ContaminatedVein(624, 645) }
Sunhunters_Vale     = { T: Extermodon, G: SolarHoneyTree(550, 481), E: true }
Tempest_Desert      = { T: Gurro }
Desolate_Desert     = { T: Appuz }
Secret_Forest_Lake  = { T: Hadis }
Gloomy_Ridge        = { E: true }
Drowsy_Cave         = { T: Ketugya }

## == Saturday ==
Helonia_Coast       = { W: Forest_Beetle(208, 189),}
Crescent_Hill       = { T: Bayin, G: CrescentFlower(713, 305) }
Cactakara_Forest    = { W: East_City_Hunter(169, 460), T: TheMurderlator, G: ColorfulWaterMushroom(511, 483), MagneticFerrousOre(151, 218), E: true }
Demarech_Mine       = { T: DNG(solo), G: DemarechFlower(532, 346) }
Triatio_Highlands   = { W: Armored_Dimetrodon(710, 258), T: Stingey, E: true }
Ventos_Prairie      = { W: Windrunner_Jerboa(494, 842), T: Dullas, DNG(solo), G: RedOre(849, 335), E: true }
Oblitus_Wood        = { W: Ghostweep_Zombie(760, 489), E: true }
Star_Sand_Desert    = { T: Kelosa, DNG(solo), G: Grapevine(408, 318) }
Vultures_Vale       = { E: true }
Rainmist_Reach      = { W: Spore_Fairy(746, 444) }
Emarald_Marsh       = { T: Zagon, G: EmeraldMarshMineral(409, 232), E: true }
Starstruck_Plateau  = { W: Undead_Warrior(422, 423), G: FragrantSnowdrop(228, 455), E: true }
Silent_Ice_Field    = { T: Roli }
Port_Morton         = { E: true }
Viridian_Steppe     = { W: Sharp_Horndeer(575, 411), E: true }
Candetonn_Hill      = { T: Dmitri }
Viridian_Steppe     = { G: Windtree(177, 251), E: true }
Desolate_Valley     = { W: Soulwrenching_Shadowling(192, 708), T: Roalbarn }
Tanglevine_Cascades = { E: true }
Sunhunters_Vale     = { T: Tavorth }
Chronology_Forest   = { G: CrystalJellyEgg(266, 669), MoonHaloStone(712, 506), E: true }
Tempest_Desert      = { T: Sonikake, E: true }
Desolate_Desert     = { T: Tomas }
Frigga_Peak         = { G: FeatheredPlant(210, 189) }
Secret_Forest_Lake  = { T: Barisbo, G: SparklingMineral(506, 682) } 
Gloomy_Ridge        = { G: BrocadeFlower(411, 368) }
Drowsy_Cave         = { T: Mahart }

## == Sunday ==
Port_Skandia        = { E: true }
Crescent_Hill       = { W: Drunken_Flower_Beetle(700, 257), T: Doniland, G: SmallBirdsNest(703, 513), E: true }
Cactakara_Forest    = { W: Ornery_Goat(455, 512), G: BerryBush(239, 335) }
Demarech_Mine       = { T: Arrel, G: BirdPatternedOre(711, 621), E: true }
Candeo_Marsh        = { E: true }
Triatio_Highlands   = { W: Argus_Beastmaster(533, 557), T: Gordon, DNG(solo), G: DesertVine(894, 527) }
Ventos_Prairie      = { W: Armored_Rhino(328, 573), T: Leon, DNG(solo)}
Oblitus_Wood        = { T: DNG(solo), G: MoltenOre(118, 106) }
Star_Sand_Desert    = { W: Imperial_Moa(236, 783), T: Serge, G: WildBirdsNest(294, 791), E: true }
Blizzard_Berg       = { E: true }
Rainmist_Reach      = { W: Sandworm_Tunneler(183, 516) }
Emerald_Marsh       = { T: Rumeon }
Starstruck_Plateau  = { W: Dark_Griffin(512, 632) }
Silent_Ice_Field    = { T: Ranya, G: ScallopCluster(193, 701), ArcticSeaCrystallCluster(754, 480), E: true }
Candetonn_Hill      = { T: Houston, E: true }
Viridian_Steppe     = { W: Zingaro_Rebel(379, 573) }
Desolate_Valley     = { T: Roche, G: Bellflower(381, 602), E: true }
Sunhunters_Vale     = { T: Caesarius, E: true }
Chronology_Forest   = { G: TimeCellar(554, 284), AncientCrushedOre(461, 444), E: true }
Tempest_Desert      = { T: Elbaman }
Frigga_Peak         = { G: ApostleCocoon(802, 779) }
Desolate_Desert     = { T: Celia }
Secret_Forest_Lake  = { G: GoldNugget(759, 719) }
Gloomy_Ridge        = { G: DrizzleGrass(253, 297) }
Drowsy_Cave         = { T: Ajiles, E: true }




